name: Rust
on:
  push: { }

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Setup Libudev
        run: sudo apt-get install -y libudev-dev
      - name: Set up Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        name: Cache dependencies
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
